### PR TITLE
Migrate from class to hooks

### PR DESCRIPTION
**Pull request by aarongarciah**
### Breaking changes

Drop support for React < 16.8.0. Users need to type the ref differently since it isn't a class component anymore:

```diff
-const ref = React.useRef<Editor>(null);
+const ref = React.useRef<React.ComponentRef<typeof Editor>>(null);
```

In practice, very few projects should be impacted by this change:

SCR-20240702-uqng

https://tools-public.mui.com/prod/pages/npmVersion?package=react-dom

I believe it's time. React 19 continues to move away from class components, e.g. https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-removing-legacy-context.

### What changes

- Refactors the component from class to function and stops using `defaultProps`.
  - Uses `useImperativeHandle` to expose the `session` object instead of a class property. 
- Updates the example to use a function component.
- Updates the type declarations.

Future work:
- Prepare the library for React 19 by using `ref` as a prop. This requires dependency updates and other changes that should be addressed in a future PR.

### Context 

While [upgrading](https://github.com/mui/material-ui/pull/42047) the material-ui repository to React 18.3.1, we were getting rid off `defaultProps` since React 18.3 started warning about `defaultProps` being deprecated on function components. Because Emotion copies the property into its function instance https://github.com/emotion-js/emotion/issues/3184, a warning is triggered. Emotion should fix this, but we might as well modernize this component.

### Test plan

All functionality should be intact. No expected changes. Run the example locally (`yarn example`) and compare it to https://react-simple-code-editor.github.io/react-simple-code-editor. Everything should work as expected.

I tested the material-ui docs locally and it works as expected.

cc @DiegoAndai

### CODE REVIEW

**Comment by oliviertassinari** [comment]
I will:

- do a quick smoke test to see if I can spot any regressions
- check behavior changes for existing users. See if we can release this as patch
- get myself a bit more immerse into the logic, there are more problems that I would like to see solved for the docs experience, but until we fill the docs-infra role, I'm not sure anyone on the MUI's team would want to become an expert with this dependency.

**Review by oliviertassinari — APPROVED** [review]

**Comment by oliviertassinari** [comment]
@aarongarciah The motivation for the change looks false to me though, React is only deprecating defaultProps on function components. The error you observed looks like a bug of emotion to me: https://github.com/emotion-js/emotion/issues/3184.

**Comment by oliviertassinari** [comment]
Rebased on https://github.com/react-simple-code-editor/react-simple-code-editor/pull/126.

**Comment by aarongarciah** [comment]
@oliviertassinari yes, I was surprised to see this warning given it's a class component. But, I double-checked locally before opening this PR by removing the `defaultProps` from the class component, and the warning was gone.

I also checked locally with the changes in this PR (using `file:/` to point to the local package), and the warning is gone.

**Comment by oliviertassinari** [comment]
@aarongarciah I agree, this PR will make the warning go away. My point is that it's not the root problem. This change should have the equivalent impact:

```diff
diff --git a/docs/src/modules/components/DemoEditor.tsx b/docs/src/modules/components/DemoEditor.tsx
index 25680a5d75..fb52af1f9e 100644
--- a/docs/src/modules/components/DemoEditor.tsx
+++ b/docs/src/modules/components/DemoEditor.tsx
@@ -63,6 +63,8 @@ const StyledSimpleCodeEditor = styled(SimpleCodeEditor)(({ theme }) => ({
   },
 }));

+delete StyledSimpleCodeEditor.defaultProps;
+
 interface DemoEditorProps extends React.HTMLAttributes<HTMLDivElement> {
   children: React.ReactNode;
   copyButtonProps: {};
```

**Pull request merged**
